package com.zpkdxgames.plexonquests.objective;

public enum ObjectiveType {
    BREAK_BLOCK,
    PLACE_BLOCK,
    KILL_ENTITY,
    DAMAGE_ENTITY,
    HARVEST_CROP,
    CATCH_FISH,
    CRAFT_ITEM,
    SMELT_ITEM,
    ENCHANT_ITEM,
    BREW_POTION,
    PLAY_TIME,
    TRAVEL_DISTANCE,
    VISIT_WORLD,
    COMPLETE_ADVANCEMENT,
    QUESTS_CLAIMED,
    PLEXON_RANK_UP,
    PLEXON_TOOL_LEVEL_UP,
    PLEXON_TOOL_PROGRESS,
    PLEXON_KEY_EARN,
    PLEXON_KEY_CLAIM,
    PLEXON_CRATE_OPEN,
    PLEXON_SHOP_VISIT,
    PLEXON_SHOP_RATE,
    PLEXON_SHOP_CREATE,
    PLEXON_DAILY_REWARD_CLAIM
}

